### ISSUE TITLE
data/local-authorities.csv needs updating following recent unitary authority mergers

### ISSUE THREAD

**Issue by zymurgic** [alphagov/local-links-manager#1088]
Westmorland & Furness Council
Cumberland Council
Somerset Council
North Yorkshire Council

are all recently-new unitary authorities.

note: Some services (e.g. planning, local land charges) may still handled by individual offices handling the former district council boundaries, until mergers are completed.

**Comment by KludgeKML** [comment]
Thanks for reporting!
