### ISSUE TITLE
Feature request: As a local authority link manager, let me specify a postcode get parameter, so that I can save a user re-entering their postcode.

### ISSUE THREAD

**Issue by dhilton** [alphagov/local-links-manager#68]
Background

For a lot of the local authority style services, the first step a user has is to enter their postcode, so that an LA can look to map a user to a UPRN. That then enables an LA to present the correct and timely information about a service to a user. Currently, if a user comes into a local authority via gov.uk local links, a user has to perform a double entry of their postcode in many occurrences, for example in Bath & North East Somerset when are my bins collected flow: 

https://isharemaps.bathnes.gov.uk/atmycouncil.aspx?gissearchlabel=Find+local+information&atTxtStreet=POSTCODE&myarea%3abtnSearch=Search

That would then present a user with a list of addresses.

If you could allow some sort of variable substitution in the URL specified, then we could collectively (national & local gov) save users some time.

**Comment by sihugh** [comment]
Hi Dan, thanks for your suggestion.

We think the biggest impact we can have for end users is to improve the quality and coverage of the link data, so our focus is on:
- Making Local Links Manager easy to use for an admin user
- Comprehensively checking the links to ensure that they are reliable.

We have a good idea of the things we need to do to meet those needs and we're prioritising those at present.

We also think (looking at our current data) that your suggestion is quite specific to an individual local transaction and may only be relevant to certain council's websites.  I'm afraid we're not able to prioritise this in our current roadmap.
